name: python 3.7
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scikit-learn
  - matplotlib
  - pandas
  - tensorflow
  - nltk
  - pillow
  - pytorch-cpu
  - torchvision-cpu
  
